### ISSUE TITLE
Overflow issue

### ISSUE THREAD

**Issue by max107** [github/government.github.com#641]
![screen shot 2017-12-26 at 13 36 07](https://user-images.githubusercontent.com/862272/34354796-db9e6fe2-ea41-11e7-88cb-45f91130d3de.png)
![screen shot 2017-12-26 at 13 36 17](https://user-images.githubusercontent.com/862272/34354799-df629aae-ea41-11e7-8b22-ef6fba4b5d6a.png)

Solution:

remove negative margins:

```scss
.featured-orgs {
  max-height: 348px;
  overflow: hidden;
  text-align: center;
}
```
